import '../entities/request_auth_draft.dart';
import '../entities/request_key_value.dart';
import 'build_basic_authorization_header_use_case.dart';
import 'build_bearer_authorization_header_use_case.dart';

class SyncRequestAuthHeadersUseCase {
  const SyncRequestAuthHeadersUseCase({
    BuildBasicAuthorizationHeaderUseCase
    buildBasicAuthorizationHeaderUseCase =
        const BuildBasicAuthorizationHeaderUseCase(),
    BuildBearerAuthorizationHeaderUseCase
    buildBearerAuthorizationHeaderUseCase =
        const BuildBearerAuthorizationHeaderUseCase(),
  }) : _buildBasicAuthorizationHeaderUseCase =
           buildBasicAuthorizationHeaderUseCase,
       _buildBearerAuthorizationHeaderUseCase =
           buildBearerAuthorizationHeaderUseCase;

  final BuildBasicAuthorizationHeaderUseCase
  _buildBasicAuthorizationHeaderUseCase;
  final BuildBearerAuthorizationHeaderUseCase
  _buildBearerAuthorizationHeaderUseCase;

  /// Synchronizes editor headers with the currently selected auth mode.
  List<KeyValueItem> call({
    required List<KeyValueItem> headers,
    required RequestAuthDraft auth,
  }) {
    final headersWithoutGeneratedAuthorization =
        _removeGeneratedAuthorizationHeader(headers);

    return switch (auth.type) {
      AuthType.basic => _syncBasicAuthorizationHeader(
        headersWithoutGeneratedAuthorization,
        auth.basic,
      ),
      AuthType.bearerToken => _syncBearerAuthorizationHeader(
        headersWithoutGeneratedAuthorization,
        auth.bearerToken,
      ),
      _ => List<KeyValueItem>.unmodifiable(headersWithoutGeneratedAuthorization),
    };
  }

  /// Removes only the Authorization row previously generated by editor auth flows.
  List<KeyValueItem> _removeGeneratedAuthorizationHeader(
    List<KeyValueItem> headers,
  ) {
    return headers
        .where((header) => !header.isSystemGeneratedAuthorizationHeader)
        .toList(growable: false);
  }

  /// Collapses Authorization rows to one system-generated Basic header when credentials are complete.
  List<KeyValueItem> _syncBasicAuthorizationHeader(
    List<KeyValueItem> headers,
    BasicAuthDraft basicAuth,
  ) {
    final authorizationValue = _buildBasicAuthorizationHeaderUseCase(basicAuth);
    if (authorizationValue == null) {
      return List<KeyValueItem>.unmodifiable(headers);
    }

    final nextHeaders = <KeyValueItem>[];
    var inserted = false;

    for (final header in headers) {
      if (_isAuthorizationHeader(header)) {
        if (!inserted) {
          nextHeaders.add(
            _buildGeneratedAuthorizationHeader(
              value: authorizationValue,
              description: basicAuthSystemGeneratedHeaderDescription,
            ),
          );
          inserted = true;
        }
        continue;
      }

      nextHeaders.add(header);
    }

    if (!inserted) {
      nextHeaders.add(
        _buildGeneratedAuthorizationHeader(
          value: authorizationValue,
          description: basicAuthSystemGeneratedHeaderDescription,
        ),
      );
    }

    return List<KeyValueItem>.unmodifiable(nextHeaders);
  }

  /// Collapses Authorization rows to one system-generated Bearer header when the token is present.
  List<KeyValueItem> _syncBearerAuthorizationHeader(
    List<KeyValueItem> headers,
    BearerTokenAuthDraft bearerTokenAuth,
  ) {
    final authorizationValue = _buildBearerAuthorizationHeaderUseCase(
      bearerTokenAuth,
    );
    if (authorizationValue == null) {
      return List<KeyValueItem>.unmodifiable(headers);
    }

    final nextHeaders = <KeyValueItem>[];
    var inserted = false;

    for (final header in headers) {
      if (_isAuthorizationHeader(header)) {
        if (!inserted) {
          nextHeaders.add(
            _buildGeneratedAuthorizationHeader(
              value: authorizationValue,
              description: bearerTokenSystemGeneratedHeaderDescription,
            ),
          );
          inserted = true;
        }
        continue;
      }

      nextHeaders.add(header);
    }

    if (!inserted) {
      nextHeaders.add(
        _buildGeneratedAuthorizationHeader(
          value: authorizationValue,
          description: bearerTokenSystemGeneratedHeaderDescription,
        ),
      );
    }

    return List<KeyValueItem>.unmodifiable(nextHeaders);
  }

  /// Builds the single Authorization row that represents the active auth mode.
  KeyValueItem _buildGeneratedAuthorizationHeader({
    required String value,
    required String description,
  }) => KeyValueItem(
    key: 'Authorization',
    value: value,
    isEnabled: true,
    description: description,
  );

  /// Returns true when the header key targets Authorization regardless of letter casing.
  bool _isAuthorizationHeader(KeyValueItem header) =>
      header.key.trim().toLowerCase() == 'authorization';
}
