import 'package:equatable/equatable.dart';

enum KeyValueItemType { text, file }

enum RequestHeaderSource { user, systemAuth, systemAws }

const basicAuthSystemGeneratedHeaderDescription = 'Generated by Basic auth';
const bearerTokenSystemGeneratedHeaderDescription =
    'Generated by Bearer token auth';
const digestAuthSystemGeneratedHeaderDescription = 'Generated by Digest auth';
const ntlmAuthSystemGeneratedHeaderDescription = 'Generated by NTLM auth';
const jwtAuthSystemGeneratedHeaderDescription = 'Generated by JWT auth';
const jwtAuthSystemGeneratedQueryParameterDescription = 'Generated by JWT auth';
const awsSystemGeneratedHeaderDescription = 'Generated by AWS auth';
const apiKeySystemGeneratedHeaderDescription = 'Generated by API Key auth';
const apiKeySystemGeneratedQueryParameterDescription =
    'Generated by API Key auth';
const oauth2SystemGeneratedHeaderDescription = 'Generated by OAuth 2.0 auth';
const oauth2SystemGeneratedQueryParameterDescription =
    'Generated by OAuth 2.0 auth';
const oauth1SystemGeneratedHeaderDescription = 'Generated by OAuth 1.0a auth';
const hawkSystemGeneratedHeaderDescription = 'Generated by Hawk auth';
const oauth1SystemGeneratedQueryParameterDescription =
    'Generated by OAuth 1.0a auth';
const bodyContentTypeSystemGeneratedHeaderDescription =
    'Generated by body editor';

class KeyValueItem extends Equatable {
  const KeyValueItem({
    required this.key,
    required this.value,
    this.isEnabled = true,
    this.type = KeyValueItemType.text,
    this.contentType = '',
    this.description = '',
    this.source = RequestHeaderSource.user,
    this.systemTag = '',
  });

  final String key;
  final String value;
  final bool isEnabled;
  final KeyValueItemType type;
  final String contentType;
  final String description;
  final RequestHeaderSource source;
  final String systemTag;

  /// Returns true when the item key has meaningful user input.
  bool get hasKey => key.trim().isNotEmpty;

  /// Returns true when the item value or file path has meaningful user input.
  bool get hasValue => value.trim().isNotEmpty;

  /// Returns true when the item can participate in request resolution.
  bool get isComplete => isEnabled && hasKey && hasValue;

  /// Creates a new key-value item with any updated editor fields applied.
  KeyValueItem copyWith({
    String? key,
    String? value,
    bool? isEnabled,
    KeyValueItemType? type,
    String? contentType,
    String? description,
    RequestHeaderSource? source,
    String? systemTag,
  }) => KeyValueItem(
    key: key ?? this.key,
    value: value ?? this.value,
    isEnabled: isEnabled ?? this.isEnabled,
    type: type ?? this.type,
    contentType: contentType ?? this.contentType,
    description: description ?? this.description,
    source: source ?? this.source,
    systemTag: systemTag ?? this.systemTag,
  );

  @override
  List<Object> get props => [
    key,
    value,
    isEnabled,
    type,
    contentType,
    description,
    source,
    systemTag,
  ];
}

typedef RequestKeyValue = KeyValueItem;

extension RequestKeyValueMetadata on KeyValueItem {
  /// Returns true when this header row is managed by the Basic auth editor flow.
  bool get isBasicAuthSystemGeneratedHeader =>
      (source == RequestHeaderSource.systemAuth && systemTag == 'basicAuth') ||
      description == basicAuthSystemGeneratedHeaderDescription;

  /// Returns true when this header row is managed by the Bearer auth editor flow.
  bool get isBearerTokenSystemGeneratedHeader =>
      (source == RequestHeaderSource.systemAuth && systemTag == 'bearerAuth') ||
      description == bearerTokenSystemGeneratedHeaderDescription;

  /// Returns true when this header row is managed by the Digest auth flow.
  bool get isDigestAuthSystemGeneratedHeader =>
      (source == RequestHeaderSource.systemAuth && systemTag == 'digestAuth') ||
      description == digestAuthSystemGeneratedHeaderDescription;

  /// Returns true when this header row is managed by the NTLM auth flow.
  bool get isNtlmAuthSystemGeneratedHeader =>
      (source == RequestHeaderSource.systemAuth && systemTag == 'ntlmAuth') ||
      description == ntlmAuthSystemGeneratedHeaderDescription;

  /// Returns true when this header row is managed by the JWT auth editor flow.
  bool get isJwtSystemGeneratedHeader =>
      (source == RequestHeaderSource.systemAuth && systemTag == 'jwtAuth') ||
      description == jwtAuthSystemGeneratedHeaderDescription;

  /// Returns true when this query-param row is managed by the JWT auth editor flow.
  bool get isSystemGeneratedJwtQueryParameter =>
      (source == RequestHeaderSource.systemAuth && systemTag == 'jwtAuth') ||
      description == jwtAuthSystemGeneratedQueryParameterDescription;

  /// Returns true when this header row is managed by the Hawk auth editor flow.
  bool get isSystemGeneratedHawkHeader =>
      (source == RequestHeaderSource.systemAuth && systemTag == 'hawkAuth') ||
      description == hawkSystemGeneratedHeaderDescription;

  /// Returns true when this Authorization row is managed by any auth editor flow.
  bool get isSystemGeneratedAuthorizationHeader =>
      isBasicAuthSystemGeneratedHeader ||
      isBearerTokenSystemGeneratedHeader ||
      isDigestAuthSystemGeneratedHeader ||
      isNtlmAuthSystemGeneratedHeader ||
      isJwtSystemGeneratedHeader ||
      isSystemGeneratedOAuth1Header ||
      isSystemGeneratedOAuth2Header ||
      isSystemGeneratedHawkHeader;

  /// Returns true when this header row is managed by the API Key auth editor flow.
  bool get isSystemGeneratedApiKeyHeader =>
      description == apiKeySystemGeneratedHeaderDescription;

  /// Returns true when this query-param row is managed by the API Key auth editor flow.
  bool get isSystemGeneratedApiKeyQueryParameter =>
      description == apiKeySystemGeneratedQueryParameterDescription;

  /// Returns true when this header row is managed by the OAuth2 auth editor flow.
  bool get isSystemGeneratedOAuth2Header =>
      description == oauth2SystemGeneratedHeaderDescription;

  /// Returns true when this query-param row is managed by the OAuth2 auth editor flow.
  bool get isSystemGeneratedOAuth2QueryParameter =>
      description == oauth2SystemGeneratedQueryParameterDescription;

  /// Returns true when this header row is managed by the OAuth1 auth editor flow.
  bool get isSystemGeneratedOAuth1Header =>
      description == oauth1SystemGeneratedHeaderDescription;

  /// Returns true when this query-param row is managed by the OAuth1 auth editor flow.
  bool get isSystemGeneratedOAuth1QueryParameter =>
      description == oauth1SystemGeneratedQueryParameterDescription;

  /// Returns true when this header row is managed by the AWS auth editor flow.
  bool get isSystemGeneratedAwsHeader =>
      (source == RequestHeaderSource.systemAws && systemTag == 'awsAuth') ||
      description == awsSystemGeneratedHeaderDescription;

  /// Returns true when this query-param row is managed by the AWS auth flow.
  bool get isSystemGeneratedAwsQueryParameter =>
      (source == RequestHeaderSource.systemAws && systemTag == 'awsAuth') ||
      description == awsSystemGeneratedHeaderDescription;

  /// Returns true when this Content-Type row is managed by the body editor flow.
  bool get isSystemGeneratedContentTypeHeader =>
      description == bodyContentTypeSystemGeneratedHeaderDescription;

  /// Returns true when this row is managed by any editor-generated sync flow.
  bool get isAnySystemGeneratedHeader =>
      isSystemGeneratedAuthorizationHeader ||
      isSystemGeneratedApiKeyHeader ||
      isSystemGeneratedAwsHeader ||
      isSystemGeneratedContentTypeHeader;

  /// Returns the auth label shown beside editor-generated Authorization rows.
  String? get systemGeneratedAuthorizationLabel => switch (description) {
    basicAuthSystemGeneratedHeaderDescription => 'Basic',
    bearerTokenSystemGeneratedHeaderDescription => 'Bearer',
    digestAuthSystemGeneratedHeaderDescription => 'Digest',
    ntlmAuthSystemGeneratedHeaderDescription => 'NTLM',
    jwtAuthSystemGeneratedHeaderDescription => 'JWT',
    awsSystemGeneratedHeaderDescription => 'AWS',
    oauth1SystemGeneratedHeaderDescription => 'OAuth 1.0a',
    oauth2SystemGeneratedHeaderDescription => 'OAuth 2.0',
    hawkSystemGeneratedHeaderDescription => 'Hawk',
    _ => null,
  };

  /// Returns the badge label shown beside supported system-generated header rows.
  String? get systemGeneratedHeaderLabel => switch (description) {
    basicAuthSystemGeneratedHeaderDescription => 'Basic',
    bearerTokenSystemGeneratedHeaderDescription => 'Bearer',
    digestAuthSystemGeneratedHeaderDescription => 'Digest',
    ntlmAuthSystemGeneratedHeaderDescription => 'NTLM',
    jwtAuthSystemGeneratedHeaderDescription => 'JWT',
    oauth1SystemGeneratedHeaderDescription => 'OAuth 1.0a',
    oauth2SystemGeneratedHeaderDescription => 'OAuth 2.0',
    hawkSystemGeneratedHeaderDescription => 'Hawk',
    awsSystemGeneratedHeaderDescription => 'AWS',
    apiKeySystemGeneratedHeaderDescription => 'API Key',
    _ => null,
  };
}
